### ISSUE TITLE
Implement extra frontmatter options

### ISSUE THREAD

**Issue by AdrianSimionov** [AdrianSimionov/obsidian-mindmap-nextgen#19]
With the exception of `extraJs` and `extraCss`, implement the options from the below link as frontmatter options:

https://markmap.js.org/docs/json-options

**Comment by MasterTuto** [comment]
I mean, how would the color options, such as color freeze cope with the already implemented feature? I mean, the color linked to the depth.

Also, would you want it to be implemented in the settings tab or it reading this options directly form the markdown file?

**Comment by MasterTuto** [comment]
I propose adding to the settings tab a select option (dropdown), just like the split direction one, to select between "branch based color" and "depth based color". Our way, the implemented one, is using the depth based color (all nodes in a depth has the same color) and the "branch based color" is the default way, which sets a random color (they also provide a function to apply this color, which I am using) to a branch and freezes it so that all children has the same color (or let's it forever random).

About how would this settings be set, I propose adding them to settings tap, a switch to enable/disable them, and if they are present in the file, the settings written in the markdown file itself must override the ones set in the settings tab.

**Comment by AdrianSimionov** [comment]
I agree, we can add the same settings as front-matter and have precedence if set, otherwise use default of the value set in settings for the whole plugin.
